name: main
on:
  push:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - run: mvn -B '-Dtest=!ApplicationTests' verify